In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv("ST-1/student_data_raw_2000.csv")
df.head()

,StudentID,Student_Name,City,C++_Score,Deep_Learning_Hours,Cloud_Hackathon,Placed_Tech
0,2860,Amit Patel,NEW DELHI,78.9,-37.6,No,0.0
1,1353,Rahul Kumar,ghaziabad,76.7,NaN,Yes,1.0
2,2333,Vikram Patel,Gorakhpur,104.4,-40.0,Yes,1.0
3,1905,Amit Joshi,NEW DELHI,42.7,32.8,Yes,0.0
4,2289,Kavya Kumar,Gorakhpur,100.5,50.7,No,1.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   StudentID            2000 non-null   int64
 1   Student_Name         2000 non-null   object
 2   City                 2000 non-null   object
 3   C++_Score            1790 non-null   float64
 4   Deep_Learning_Hours  1746 non-null   float64
 5   Cloud_Hackathon      1894 non-null   object
 6   Placed_Tech          1955 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 109.5+ KB

In [12]:
df.describe()

         StudentID    C++_Score  Deep_Learning_Hours  Placed_Tech
count  2000.000000  1790.000000          1746.000000  1955.000000
mean   1973.488500    99.183911            35.693585     0.461381
std     561.240592   122.307750            20.803892     0.498634
min    1000.000000    26.400000           -60.900000     0.000000
25%    1487.750000    65.600000            32.200000     0.000000
50%    1973.500000    76.100000            39.400000     0.000000
75%    2458.250000    87.400000            46.500000     1.000000
max    2949.000000   993.300000            71.400000     1.000000